site_name: Fusion 360 SVG postprocessor
site_url:
site_author: Jakub Andrýsek
site_description: >-
  Project page for SVG postprocessor for Fusion 360 CAM that generates SVG files for laser cutting.
  Postprocessor supports laser-width compensation and cutting and engraving modes by using different laser tools.

# Repository
repo_name: RoboticsBrno/Fusion360-SVG-postprocessor
repo_url: https://github.com/RoboticsBrno/Fusion360-SVG-postprocessor

# Copyright
copyright: Copyright © 2023 RoboticsBrno

theme:
  name: material
  language: en
  logo: assets/robotarna.png
  favicon: assets/robotarna.png
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: orange
      accent: orange

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/RoboticsBrno
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/RobotikaBrno
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/robotarna
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@robotikabrno-robotarnaasps2392
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_robotarna_
#    analytics:
#        provider: google
#        property: G-XXXXXXXXXX

use_directory_urls: True

plugins:
  - search
  - glightbox
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      languages:
        default:
          name: Default (en)
          build: true
        cs:
          name: Czech (cs)
          build: true
          site_name: "Fusion 360 - SVG postprocessor"
      # nav_translations:
      #   fr:
      #     Topic1: Sujet1
      #     Topic2: Sujet2
  - git-revision-date-localized


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: 'README.md'